[package]
name = "cas-core-lib"
version = "0.1.7"
edition = "2021"
description = "This is a Rust library providing external facing functions to performant and trusted encryption in Rust"
license = "Apache-2.0"

[lib]
name="cas-core-lib"
path = "src/lib.rs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.1"
argon2 = "0.4.1"
base64 = "0.20.0"
bcrypt = "0.13.0"
rand = "0.8.5"
rand_07 = { package = "rand", version = "0.7.0" }
rsa = "0.7.2"
scrypt = "0.10.0"
sha3 = "0.10.6"
md-5 = "0.10.5"
hmac = "0.12.1"
sha2 = "0.10.6"
blake2 = "0.10.6"
libc = "0.2.146"

[profile.dev.package.num-bigint-dig]
opt-level = 3

[dependencies.ed25519-dalek]
version = "1"
